name: Terraform img builder

on:
  workflow_dispatch:

jobs:
  docker:
    uses: GithubActionsPrueba2/repoPrueba2/.github/workflows/terraform.yml@main
    with: 
      aws-region: "eu-west-3"
    secrets: inherit
