name: Docker img builder

on:
  workflow_dispatch:

jobs:
  docker:
    uses: GithubActionsPrueba2/repoPrueba2/.github/workflows/docker.yml@main
    with: 
      image_name: my-awesome-app
      tag: $GITHUB_RUN_NUMBER
    secrets: inherit
